### PR TITLE
tooltip content darker

### LINKED ISSUE #83: Map panel -- tooltip text too light with Light theme
The tooltip text on the map panel hover tooltips is not very readable when Grafana is set to the _Light_ theme:
Screen Shot 2020-05-05 at 10 25 05 AM

Not sure if it's possible to set colour conditionally based on the theme setting -- I would think there are theme variables available, and this would be `secondaryTextColor` or something like that.

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #83 
add text colour to the light theme css

### CODE REVIEW

**Comment by CarlosNZ** [comment]
I notice this was to be merged into `develop`, whereas #86 was to merge to`master` -- was this intentional? 

If so, once you've merged #86 (I'll let you do it), should we merge develop into master? Once we've got both these fixes in the one branch, I'll update the LAOS Covid dashboard. :)

**Comment by mark-prins** [comment]
oh. darn. usually I go `develop` => `master`
how about we merge this to `develop`, then merge `develop` => `master` and then just merge `master` back to `develop`? that gets everything up to date

**Comment by CarlosNZ** [comment]
Haven't merged #86 yet, so should be able to just merge that then `develop` -> `master` and that should be enough?

**Comment by mark-prins** [comment]
yep, sounds perfect

**Pull request merged**
